name: react CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Node.js for deployment
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{secrets.AWS_REGION}}
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_REGION: ${{secrets.AWS_REGION}}

      - name: Install Dependencies
        uses: actions/setup-node@v2
        with:
          node-version: '20'
        run: npm install

      - name: Build React App
        uses: actions/setup-node@v2
        with:
          node-version: '20'
        run: npm run build

      - name: Upload to S3
        uses: actions/setup-node@v2
        with:
          node-version: '20'
        run: aws s3 sync build/ s3://${{secrets.AWS_S3_BUCKET}}
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js for build
        uses: actions/setup-node@v2
        with:
          node-version: '20'
        run: npm install
